---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp/css * $DEPLOYPATH
    - /bin/cp/js * $DEPLOYPATH
    - /bin/cp/php * $DEPLOYPATH
    - /bin/cp/images * $DEPLOYPATH
    - /bin/cp/fonts * $DEPLOYPATH
    - /bin/cp/.htaccess * $DEPLOYPATH
